### ISSUE TITLE
请问什么时候开源呢？

### ISSUE THREAD

**Issue by liweizhen111** [ai-agi/HiCL#1]
您好，最近研读了您这篇论文，觉得您的工作对我非常有启发，希望能够实践、重现一下实验。所以，请问下什么时候能够开源呢？感谢！

**Comment by ai-agi** [comment]
hi @liweizhen111 we have already released the first code version of HiCL, enjoy!

**Comment by liweizhen111** [comment]
thanks for your nice work!
